- name: Check if Telnet is enabled
- hosts: cisco

  tasks:
  - name: TELNET CHECK
    ios_command:
      authorize: yes
      commands:
        - show run | beg line vty
    register: vty

  - debug: var=vty.stdout_lines
